[colors.primary]
background = "#07080A"
foreground = "#E2E4E9"

[colors.cursor]
cursor = "#FFFFFF"
text = "#07080A"

[colors.selection]
background = "#1A1D24"
text = "#FFFFFF"

[colors.normal]
black = "#353942"
red = "#8C5C5C"
green = "#5C6B5C"
yellow = "#8C7E5C"
blue = "#5C6B7C"
magenta = "#785C7D"
cyan = "#5C7878"
white = "#E2E4E9"

[colors.bright]
black = "#353942"
red = "#8C5C5C"
green = "#5C6B5C"
yellow = "#8C7E5C"
blue = "#5C6B7C"
magenta = "#785C7D"
cyan = "#5C7878"
white = "#FFFFFF"
