background-opacity = 0.60
window-padding-x = 10
window-padding-y = 15

background = #07080A
foreground = #E2E4E9
cursor-color = #FFFFFF
selection-background = #1A1D24
selection-foreground = #FFFFFF

palette = 0=#07080A
palette = 1=#8C5C5C
palette = 2=#5C6B5C
palette = 3=#8C7E5C
palette = 4=#5C6B7C
palette = 5=#785C7D
palette = 6=#5C7878
palette = 7=#E2E4E9

palette = 8=#353942
palette = 9=#8C5C5C
palette = 10=#5C6B5C
palette = 11=#8C7E5C
palette = 12=#5C6B7C
palette = 13=#785C7D
palette = 14=#5C7878
palette = 15=#FFFFFF

copy-on-select = clipboard
