# ------------------------------------------------------------
# Pure-Latin v5.3 - Hyprland (Industrial Fade)
# Created by Daury DiCaprio | #verygoodforlife
# ------------------------------------------------------------

general {
    gaps_in = 4
    gaps_out = 8
    border_size = 2
    col.active_border = rgb(FFFFFF)
    col.inactive_border = rgba(1A1D2466)
}

decoration {
    rounding = 0
    dim_inactive = true
    dim_strength = 0.25

    blur {
        enabled = true
        size = 4
        passes = 1
        vibrancy = 0.1696
        new_optimizations = true
    }

    shadow {
        enabled = false
    }
}

animations {
    enabled = true
    bezier = easeOutQuint, 0.23, 1, 0.32, 1

    animation = windows, 1, 3.5, easeOutQuint, popin 85%
    animation = workspaces, 1, 3, easeOutQuint, fade
}

misc {
    focus_on_activate = true
    disable_hyprland_logo = true
}
